# Node.js image
FROM node:18-alpine

# Set wotking directory in conatiner
WORKDIR /app

#copy package json files to working directory
COPY package*.json ./

#install dependencies
RUN npm install

# copy source code into working directroy
COPY . .

# Copy .env file into container
# COPY site/.env .env

#Expose port app is running on
EXPOSE 3000


#Command to run the app
CMD [ "node", "app.js" ]
